# Generated by Django 6.0.1 on 2026-04-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_song_artist_remove_song_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
