# Generated by Django 6.0.1 on 2026-04-01 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Metal', 'Metal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
